---
kind: pipeline
name: pyramid_task_scheduler
steps:
- name: flake8 and black
  image: python
  commands:
    - pip install flake8 black 
    - flake8 .
    - black --diff .
    - black --check .

- name: python3-6
  image: python:3.6
  commands:
  - pip3 install .
  depends_on:
  - common

- name: python3-7
  image: python:3.7
  commands:
  - pip3 install .
  depends_on:
  - common

- name: python3-8
  image: python:3.8
  commands:
  - pip3 install .
  depends_on:
  - common

- name: python3-9
  image: python:3.9
  commands:
  - pip3 install .
  depends_on:
  - common

- name: python3-10
  image: python:3.10
  commands:
  - pip3 install .
  depends_on:
  - common

- name: build
  image: python
  commands:
    - python3 -m build
  depends_on:
  - common
  trigger:
    event:
    - push
    - pull_request
    - promote

- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    skip_build: True
  trigger:
    event:
      - promote
  depends_on:
  - common
  - python-3-6
  - python-3-7
  - python-3-8
  - python-3-9
  - python-3-10
  - test-build
