---
kind: pipeline
name: common
steps:
- name: flake8 and black
  image: python
  commands:
    - pip install flake8 black 
    - flake8 .
    - black --diff .
    - black --check .

---
kind: pipeline
name: python-3-6

steps:
- name: test
  image: python:3.6
  commands:
  - pip3 install .

depends_on:
  - common

---
kind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands:
  - pip3 install .

depends_on:
  - common

---
kind: pipeline
name: python-3-8

steps:
- name: test
  image: python:3.8
  commands:
  - pip3 install .

depends_on:
  - common

---
kind: pipeline
name: python-3-9

steps:
- name: test
  image: python:3.9
  commands:
  - pip3 install .

depends_on:
  - common

---
kind: pipeline
name: python-3-10

steps:
- name: test
  image: python:3.10
  commands:
  - pip3 install .

depends_on:
  - common

---
kind: pipeline
name: test-build
trigger:
  event:
  - push
  - pull_request

steps:
- name: build
  image: python
  commands:
    - python3 -m build

depends_on:
  - common

---
kind: pipeline
name: build-and-publish
trigger:
  event: promote

steps:
- name: build
  image: python
  commands:
    - python3 -m build

- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    skip_build: True

depends_on:
- common
- python-3-6
- python-3-7
- python-3-8
- python-3-9
- python-3-10
- test-build
