default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4' # Update me!
    hooks:
    - id: bandit

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8

-  repo: https://github.com/waisbrot/pre-commit-jsonnet.git
   rev: v1.0
   hooks:
   - id: jsonnetfmt
